from flask import Flask, request, url_for

# Flask is a micro web framework for Python
# Here we create a Flask application instance
# __name__ is a special Python variable containing the name of the current module
# This helps Flask know where to find resources like templates
app = Flask(__name__)


# ROUTE: About Page
# The @app.route decorator maps the URL path "/about" to this function
# When a user visits "/about", Flask will execute this function and return its result
@app.route("/about")
def about():
    # url_for() generates a URL to the specified endpoint (function name)
    # This prevents hardcoding URLs and handles any future route changes automatically
    index_url = url_for('index')  # Generate URL to the index page

    # Here we're returning a multi-line f-string containing HTML
    # f-strings allow us to embed Python expressions inside curly braces {}
    # Note the double curly braces {{ }} for CSS - these become single braces in the output
    return f"""
    <!DOCTYPE html>
    <html>
        <head>
            <title>About This Flask App</title>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; }}
                .container {{ max-width: 800px; margin: 0 auto; }}
                h1 {{ color: #333; }}
                .nav {{ margin-bottom: 20px; }}
                .nav a {{ margin-right: 15px; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="nav">
                    <!-- Navigation menu with links generated by url_for -->
                    <a href="{index_url}">Home</a>
                    <a href="{url_for('hello_from_flask')}">Hello</a>
                    <a href="{url_for('goodbye_from_flask')}">Goodbye</a>
                </div>

                <h1>About This Flask Application</h1>
                <p>This is a simple Flask web application created as a learning exercise.</p>

                <h2>Features</h2>
                <ul>
                    <li>Dynamic routing with parameters</li>
                    <li>GET and POST request handling</li>
                    <li>URL generation with url_for</li>
                    <li>Simple HTML templating</li>
                </ul>

                <h2>Technologies Used</h2>
                <ul>
                    <li>Python</li>
                    <li>Flask</li>
                    <li>HTML</li>
                </ul>

                <p>Created by: Your Name</p>
                <!-- Dynamic date generation using Python's datetime module -->
                <!-- __import__() is used here to import a module dynamically -->
                <p>Last Updated: {__import__('datetime').datetime.now().strftime('%B %d, %Y')}</p>
            </div>
        </body>
    </html>
    """


# ROUTE: Hello Page
# Simple route that returns a plain text greeting
@app.route("/hello")
def hello_from_flask():
    return "Hello from Flask!"


# ROUTE: Goodbye Page
# Another simple route returning plain text
@app.route("/bye")
def goodbye_from_flask():
    return "Goodbye, farewell from Flask"


# ROUTE: Index/Home Page
# The root URL "/" is mapped to this function
# This serves as the main landing page of the application
@app.route("/")
def index():
    # Generate URLs for various pages using url_for
    about_url = url_for('about')
    hello_url = url_for('hello_from_flask')
    goodbye_url = url_for('goodbye_from_flask')

    # For routes with parameters, we can provide those parameters to url_for
    # This generates URLs with the parameters already included
    echo_url = url_for('echo', word='testing')  # Will create /echo/testing
    square_url = url_for('square', number=5)  # Will create /square/5

    # Return HTML with embedded links generated by url_for
    return f"""
    <!DOCTYPE html>
    <html>
        <head>
            <title>Flask URL Examples</title>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; }}
                .container {{ max-width: 800px; margin: 0 auto; }}
                h1 {{ color: #333; }}
                .nav {{ margin-bottom: 20px; }}
                .nav a {{ margin-right: 15px; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="nav">
                    <!-- Navigation menu with dynamically generated URLs -->
                    <a href="{url_for('index')}">Home</a>
                    <a href="{hello_url}">Hello</a>
                    <a href="{goodbye_url}">Goodbye</a>
                    <a href="{about_url}">About</a>
                </div>

                <h1>URL Examples with url_for</h1>
                <ul>
                    <!-- Display both the links and the actual URLs that url_for generates -->
                    <li><a href="{hello_url}">Hello Route</a>: {hello_url}</li>
                    <li><a href="{goodbye_url}">Goodbye Route</a>: {goodbye_url}</li>
                    <li><a href="{echo_url}">Echo Route with 'testing'</a>: {echo_url}</li>
                    <li><a href="{square_url}">Square Route with number 5</a>: {square_url}</li>
                    <li><a href="{about_url}">About Page</a>: {about_url}</li>
                </ul>
            </div>
        </body>
    </html>
    """


# ROUTE: GET Text
# Simple route demonstrating a GET request handler
@app.route("/get/text")
def get_text():
    # By default, Flask routes handle GET requests
    return "This is a GET request."


# ROUTE: POST Text
# Route demonstrating a POST request handler
# The methods parameter specifies which HTTP methods this route accepts
@app.route("/post/text", methods=["post"])
def post_text():
    # request.data contains the raw data sent in the request body
    data_sent = request.data
    # Return a response that includes the data sent by the client
    return "This is POST request. The data you sent was" + data_sent


# ROUTE: Echo with Variable
# This route captures a variable part of the URL as a parameter
# <string:word> defines a variable named "word" of type string
# Flask will extract this value from the URL and pass it to the function
@app.route("/echo/<string:word>")
def echo(word):
    # The captured parameter is passed as an argument to the function
    # Here we convert it to uppercase and return it
    return "Echo: " + word.upper()


# ROUTE: Square Number with Variable
# Similar to the echo route, but capturing an integer instead of a string
# <int:number> ensures that the captured value is an integer
@app.route("/square/<int:number>")
def square(number):
    # Calculate the square of the provided number
    squared = number ** 2  # ** is the exponentiation operator
    # Convert the result to a string and include it in the response
    line = "Your number squared is " + str(squared)
    return line


# ROUTE: Redirect Example
# This route demonstrates redirecting from one route to another
@app.route("/redirect-example")
def redirect_example():
    # Import the redirect function from Flask
    from flask import redirect
    # Redirect to the hello_from_flask route using url_for to generate the URL
    return redirect(url_for('hello_from_flask'))


# ROUTE: User Profile
# Route with a username parameter that generates links to related actions
@app.route("/user/<username>")
def user_profile(username):
    # Generate URLs for different actions on this user
    edit_profile_url = url_for('edit_profile', username=username)
    delete_profile_url = url_for('delete_profile', username=username)

    # Return HTML with embedded links
    return f"""
    <!DOCTYPE html>
    <html>
        <head>
            <title>User: {username}</title>
        </head>
        <body>
            <h1>Profile for {username}</h1>
            <ul>
                <li><a href="{edit_profile_url}">Edit Profile</a></li>
                <li><a href="{delete_profile_url}">Delete Profile</a></li>
                <li><a href="{url_for('index')}">Back to Home</a></li>
            </ul>
        </body>
    </html>
    """


# ROUTE: Edit Profile
# Route for editing a user profile, with username parameter
@app.route("/user/<username>/edit")
def edit_profile(username):
    return f"Edit profile page for {username}"


# ROUTE: Delete Profile
# Route for deleting a user profile, with username parameter
@app.route("/user/<username>/delete")
def delete_profile(username):
    return f"Delete profile page for {username}"


# ROUTE: Name Greeting
# This route captures a variable part of the URL as a name parameter
# This route will match any URL with a single segment that's not matched by other routes
@app.route("/<string:name>")
def home(name):
    # Generate a URL to the index page
    index_url = url_for('index')

    # Return HTML that greets the user by name
    return f"""
    <!DOCTYPE html>
    <html>
        <head>
            <title>Simple Flask App</title>
        </head>
        <body>
            <h1>Home Page</h1>
            <p>Hello {name}!</p>
            <p><a href="{index_url}">Back to Index</a></p>
        </body>
    </html>
    """


# This conditional checks if this script is being run directly (not imported)
if __name__ == "__main__":
    # Start the Flask development server
    # debug=True enables:
    # - Automatic reloading when code changes
    # - Detailed error pages
    # - Debug console for errors
    # NOTE: debug=True should NOT be used in production environments
    app.run(debug=True)